# Module with the game parameters
import numpy as np

RNG = np.random.default_rng(42)

ENDOWMENT = 10
CURRENCY = "$"

# Waiting times
WAIT_PAGE_TIME = 1.25  # Refresh interval at barrier
MAX_WAITING_SEEING_INFO = 10 # Max wait at a barrier


NUM_BIG_FIVE_QUESTIONS = 2
MAX_WAITING_BIG_FIVE_QUESTIONS = 10
MAX_WAITING_PROPOSALS = 5
MAX_WAITING_FOR_OTHER = 1.5 * MAX_WAITING_PROPOSALS
MAX_WAIT_TIME = 180

# Repetitions
NUM_BIG_FIVE_QUESTIONS = 0
MAX_NUM_WAITING_BIG_FIVE_QUESTIONS = 2
MAX_TIMEOUT_ROUNDS = 2

assert MAX_NUM_WAITING_BIG_FIVE_QUESTIONS > 1

# Waiting times
WAIT_PAGE_TIME = 1.5  # Refresh interval at barrier
TIMEOUT_PROPOSALS = 3000
TIMEOUT_WAITING_FOR_OTHER = 1.5 * TIMEOUT_PROPOSALS # Max wait at a barrier
TIMEOUT_BETWEEN_BARRIERS = 20 # Max time between barriers
TIMEOUT_WAITING_BIG_FIVE_QUESTIONS = 30
TIMEOUT_PERSONALITY_TEST = TIMEOUT_WAITING_BIG_FIVE_QUESTIONS * (NUM_BIG_FIVE_QUESTIONS + MAX_NUM_WAITING_BIG_FIVE_QUESTIONS)

# Rewards
REWARD_SCALING_FACTOR = 0.01
MAX_BONUS_REWARD = 7



# Waiting times
WAIT_PAGE_TIME = 1.5  # Refresh interval at barrier
TIMEOUT_PROPOSALS = 30
TIMEOUT_WAITING_FOR_OTHER = 1.5 * TIMEOUT_PROPOSALS # Max wait at a barrier
TIMEOUT_BETWEEN_BARRIERS = 20 # Max time between barriers
TIMEOUT_WAITING_BIG_FIVE_QUESTIONS = 30
TIMEOUT_PERSONALITY_TEST = TIMEOUT_WAITING_BIG_FIVE_QUESTIONS * (NUM_BIG_FIVE_QUESTIONS + MAX_NUM_WAITING_BIG_FIVE_QUESTIONS)


NUMBER_OF_ROUNDS = 2
NUMBER_OF_REPEATED_GAMES = 2

REWARD_SCALING_FACTOR = 0.01
MAX_BONUS_REWARD = 7
